"""Generate per-workflow model manifests from HuggingFaceDownloader nodes.

Scans backend/workflows/**/*.json for downloader nodes, extracts their
download_links (already in `URL folder [filename]` format), and writes:
  config/model_manifests/<workflow-id>.txt   one manifest per workflow
  config/model_manifests/ALL-MODELS.txt      deduplicated union

Workflow ids come from config/workflow_api.json (filename -> id); JSONs not
registered there fall back to their file stem. Run from anywhere:
  python scripts/generate_model_manifests.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = ROOT / "backend" / "workflows"
API_CONFIG = ROOT / "config" / "workflow_api.json"
OUT_DIR = ROOT / "config" / "model_manifests"

URL_RE = re.compile(r"^https?://\S+\s+\S+", re.M)


def extract_links(workflow_path: Path) -> list[str]:
    """Return manifest lines from every downloader node in one workflow JSON."""
    try:
        data = json.loads(workflow_path.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, UnicodeDecodeError):
        return []

    blobs: list[str] = []

    def collect_from_api_node(node: dict) -> None:
        if "Downloader" in str(node.get("class_type", "")):
            links = node.get("inputs", {}).get("download_links", "")
            if isinstance(links, str) and links.strip():
                blobs.append(links)

    def collect_from_ui_node(node: dict) -> None:
        if "Downloader" in str(node.get("type", "")):
            for value in node.get("widgets_values") or []:
                if isinstance(value, str) and URL_RE.search(value):
                    blobs.append(value)

    if isinstance(data, dict) and isinstance(data.get("nodes"), list):
        for node in data["nodes"]:
            if isinstance(node, dict):
                collect_from_ui_node(node)
    elif isinstance(data, dict):
        for node in data.values():
            if isinstance(node, dict):
                collect_from_api_node(node)

    lines: list[str] = []
    for blob in blobs:
        for raw in blob.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) >= 2 and parts[0].startswith("http"):
                lines.append(" ".join(parts[:3]))
    return lines


def main() -> None:
    id_by_filename: dict[str, str] = {}
    if API_CONFIG.exists():
        api = json.loads(API_CONFIG.read_text(encoding="utf-8-sig"))
        for wf_id, entry in api.items():
            filename = str(entry.get("filename", "")).replace("\\", "/")
            if filename:
                id_by_filename[filename] = wf_id

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    all_lines: dict[str, str] = {}  # key: url+folder for dedupe, value: line
    manifest_count = 0

    for wf_path in sorted(WORKFLOWS_DIR.rglob("*.json")):
        lines = extract_links(wf_path)
        if not lines:
            continue
        rel = wf_path.relative_to(WORKFLOWS_DIR).as_posix()
        wf_id = id_by_filename.get(rel, wf_path.stem)
        # sanitize id for filesystem
        safe_id = re.sub(r"[^A-Za-z0-9._-]", "_", wf_id)

        seen: set[str] = set()
        unique: list[str] = []
        for line in lines:
            parts = line.split()
            key = f"{parts[0]} {parts[1]}"
            if key not in seen:
                seen.add(key)
                unique.append(line)
            all_lines.setdefault(key, line)

        header = (
            f"# Models for workflow: {wf_id}\n"
            f"# Source: backend/workflows/{rel}\n"
            f"# Format: URL folder [filename]  (folder is relative to ComfyUI/models)\n"
            f"# Generated by scripts/generate_model_manifests.py - do not edit by hand.\n"
        )
        (OUT_DIR / f"{safe_id}.txt").write_text(header + "\n".join(unique) + "\n", encoding="utf-8")
        manifest_count += 1
        print(f"  {safe_id}.txt  ({len(unique)} models)  <- {rel}")

    all_header = (
        "# Union of all workflow model manifests (deduplicated).\n"
        "# Generated by scripts/generate_model_manifests.py - do not edit by hand.\n"
    )
    (OUT_DIR / "ALL-MODELS.txt").write_text(
        all_header + "\n".join(sorted(all_lines.values())) + "\n", encoding="utf-8",
    )
    print(f"\n{manifest_count} manifests + ALL-MODELS.txt ({len(all_lines)} unique models) -> {OUT_DIR}")


if __name__ == "__main__":
    sys.exit(main())
